# pandas入门作业

## 作业1：电商平台

In [29]:
import pandas as pd

# 创建示例数据
data = {
    '商品ID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    '商品类别': ['电子产品', '服装', '食品', '电子产品', '服装'],
    '一月销量': [120, 85, 150, 90, 110],
    '二月销量': [135, 95, 160, 80, 120],
    '三月销量': [140, 100, 170, 95, 130]
}

# 创建DataFrame，设置商品ID为索引
sales_df = pd.DataFrame(data).set_index('商品ID')

In [30]:
# 1. 查看数据集行数和列数
index = sales_df.shape[0]
print(f'数据集行数：',index)
columns = sales_df.shape[1]
print(f'数据集列数：',columns)
# 2. 获取所有商品 ID
s = sales_df.index
print(f'所有商品 ID：',s)
# 4. 获取所有列名
print(sales_df.columns)

# 6. 查看数据集行数和列数


数据集行数： 5
数据集列数： 4
所有商品 ID： Index(['P001', 'P002', 'P003', 'P004', 'P005'], dtype='object', name='商品ID')
Index(['商品类别', '一月销量', '二月销量', '三月销量'], dtype='object')


In [31]:
# 5. 转置数据集
sales_df.T

商品ID  P001 P002 P003  P004 P005
商品类别  电子产品   服装   食品  电子产品   服装
一月销量   120   85  150    90  110
二月销量   135   95  160    80  120
三月销量   140  100  170    95  130

In [32]:
# 3. 获取数据集所有值
sales_df

商品类别  一月销量  二月销量  三月销量
商品ID                        
P001  电子产品   120   135   140
P002    服装    85    95   100
P003    食品   150   160   170
P004  电子产品    90    80    95
P005    服装   110   120   130

In [33]:
# 7. 获取前三条数据
sales_df.head(3)

商品类别  一月销量  二月销量  三月销量
商品ID                        
P001  电子产品   120   135   140
P002    服装    85    95   100
P003    食品   150   160   170

In [34]:
# 8. 获取后两条数据
sales_df.tail(2)

商品类别  一月销量  二月销量  三月销量
商品ID                        
P004  电子产品    90    80    95
P005    服装   110   120   130

In [35]:
# 9. 重置索引
sales_df.reset_index()

商品ID  商品类别  一月销量  二月销量  三月销量
0  P001  电子产品   120   135   140
1  P002    服装    85    95   100
2  P003    食品   150   160   170
3  P004  电子产品    90    80    95
4  P005    服装   110   120   130

In [36]:
# 10. 以商品类别作为新的索引
sales_df.set_index('商品类别')

一月销量  二月销量  三月销量
商品类别                  
电子产品   120   135   140
服装      85    95   100
食品     150   160   170
电子产品    90    80    95
服装     110   120   130

## 作业2：学生考试成绩

In [38]:
import numpy as np

# 创建成绩数据（单位：分）
scores_data = {
    '学生ID': ['S001', 'S002', 'S003', 'S004', 'S005'],
    '数学': [85, 92, 76, 88, 95],
    '英语': [78, 85, 82, 90, 88],
    '物理': [90, 87, 91, 79, 83]
}

# 转换为ndarray（以学生ID为索引）
scores_ndarray = np.array([
    [85, 78, 90],
    [92, 85, 87],
    [76, 82, 91],
    [88, 90, 79],
    [95, 88, 83]
], dtype=np.float64)

# 设置学生ID为行索引（实际操作中可通过花式索引实现）
student_ids = np.array(['S001', 'S002', 'S003', 'S004', 'S005'])
subjects = np.array(['数学', '英语', '物理'])

In [47]:
# 查看成绩数组的维度、形状、元素类型及总个数
print(scores_ndarray.ndim)
print(scores_ndarray.shape)
print(scores_ndarray.dtype)
print(scores_ndarray.size)


2
(5, 3)
float64
15


In [46]:
# 将成绩数组转换为整数类型，并查看每个元素的字节大小
scores_ndarray.astype(dtype=np.int64)
print(scores_ndarray)
print(scores_ndarray.itemsize)

[[85. 78. 90.]
 [92. 85. 87.]
 [76. 82. 91.]
 [88. 90. 79.]
 [95. 88. 83.]]
8


In [52]:
# 计算所有学生的数学平均分、物理总分及英语最高分
print(scores_ndarray[0:, 0].mean())
print(scores_ndarray[0:, 2].sum())
print(scores_ndarray[0:, 1].max())

87.2
430.0
90.0


In [55]:
# 对物理成绩进行排序，并找到最低分的索引
print(np.argmin(scores_ndarray[:, 2]))


3


In [56]:
# 使用where函数将 90 分以上的成绩标记为 'A'，其余为 'B'
np.where(scores_ndarray > 90, 'A', 'B')

array([['B', 'B', 'B'],
       ['A', 'B', 'B'],
       ['B', 'B', 'A'],
       ['B', 'B', 'B'],
       ['A', 'B', 'B']], dtype='<U1')

In [58]:
# 计算每个学生的总分（行方向求和）与每科的平均分（列方向求平均）
print(scores_ndarray.sum(axis=1))
print(scores_ndarray.mean(axis=0))

[253. 264. 249. 257. 266.]
[87.2 84.6 86. ]


In [60]:
# 使用cumsum计算每个学生的累计得分
np.cumsum(scores_ndarray, axis=1)

array([[ 85., 163., 253.],
       [ 92., 177., 264.],
       [ 76., 158., 249.],
       [ 88., 178., 257.],
       [ 95., 183., 266.]])