# Numpy 属性
***Numpy的数组类被称为ndarray,通常被称为数组***
ndarray对象属性有:
- ndarray.shape: 数组维度
- ndarray.dtype: 数组元素类型
- ndarray.size: 数组元素个数
- ndarray.itemsize: 数组元素字节数
- ndarray.nbytes: 数组字节数
- ndarray.ndim: 数组维度
- ndarray.flags: 数组标志
- ndarray.data: 数组数据
- ndarray.strides: 数组步长
- ndarray.base: 数组基
- ndarray.T: 数组转置
- ndarray.flat: 迭代数组元素
- ndarray.ctypes: 创建一个ctypes.Array对象
- ndarray.item: 获取数组元素
- ndarray.itemset: 设置数组元素
- ndarray.tolist: 数组转列表
- ndarray.tostring: 数组转字符串
- ndarray.tobytes: 数组转字节
- ndarray.tofile: 数组转文件
- ndarray.dump: 数组转文件
- ndarray.dumps: 数组转字符串
- ndarray.astype: 数组转类型
- ndarray.copy: 数组复制
- ndarray.view: 数组视图
- ndarray.fill: 数组填充
- ndarray.reshape: 数组reshape
- ndarray.ravel: 数组ravel
- ndarray.transpose: 数组转置
- ndarray.take: 数组take
- ndarray.put: 数组put
- ndarray.repeat: 数组repeat
- ndarray.choose: 数组choose
- 

In [1]:
import numpy as np

In [2]:
# 创建一个ndarray数组
arr = np.arange(20).reshape(1,4,5)
print(arr)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [3]:

# 1-2 常用属性演示
# shape 数组维度
print(arr.shape) # (3,5,4) 3行(5行,4列)
# dtype 数组元素类型
print(arr.dtype)
# size 数组元素个数
print(arr.size)
# itemsize 数组元素字节数
print(arr.itemsize)
# nbytes 数组字节数
print(arr.nbytes)
# ndim 数组维度
print(arr.ndim)
# flags 数组标志
print(arr.flags)
# data 数组数据
print(arr.data.tolist())


(1, 4, 5)
int64
20
8
160
3
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]]
