# 1.numpy内置函数

## 1.1 np.ceil() 向上取整

In [148]:
import numpy as np

randn = np.random.randn(5, 5)

print(randn)

[[-0.25853616 -1.95340579  1.02064545 -0.37275931 -0.85204976]
 [-0.39877131  0.40130583 -0.92628652  0.30489585 -0.67111815]
 [-1.45565514 -0.03283583  0.83395511 -0.41289642  1.98152785]
 [-1.76297445 -1.85228563  0.97942365 -0.08771742 -0.07937717]
 [-0.6170346   0.02158654 -0.99121582  0.83269175 -0.28841781]]


In [149]:
print(np.ceil(randn))

[[-0. -1.  2. -0. -0.]
 [-0.  1. -0.  1. -0.]
 [-1. -0.  1. -0.  2.]
 [-1. -1.  1. -0. -0.]
 [-0.  1. -0.  1. -0.]]


## 1.2 np.floor() 向下取整

In [150]:
print(np.floor(randn))

[[-1. -2.  1. -1. -1.]
 [-1.  0. -1.  0. -1.]
 [-2. -1.  0. -1.  1.]
 [-2. -2.  0. -1. -1.]
 [-1.  0. -1.  0. -1.]]


## 1.3 np.rint() 四舍五入

In [151]:
print(np.rint(randn))

[[-0. -2.  1. -0. -1.]
 [-0.  0. -1.  0. -1.]
 [-1. -0.  1. -0.  2.]
 [-2. -2.  1. -0. -0.]
 [-1.  0. -1.  1. -0.]]


## 1.4 np.abs() 绝对值

In [152]:
print(np.abs(randn))

[[0.25853616 1.95340579 1.02064545 0.37275931 0.85204976]
 [0.39877131 0.40130583 0.92628652 0.30489585 0.67111815]
 [1.45565514 0.03283583 0.83395511 0.41289642 1.98152785]
 [1.76297445 1.85228563 0.97942365 0.08771742 0.07937717]
 [0.6170346  0.02158654 0.99121582 0.83269175 0.28841781]]


## 1.5 np.multiply 矩阵对应位相乘

In [153]:
# 相当于 print(randn * randn)
print(np.multiply(randn, randn))

[[6.68409483e-02 3.81579417e+00 1.04171713e+00 1.38949506e-01
  7.25988792e-01]
 [1.59018561e-01 1.61046372e-01 8.58006719e-01 9.29614784e-02
  4.50399569e-01]
 [2.11893189e+00 1.07819157e-03 6.95481123e-01 1.70483457e-01
  3.92645260e+00]
 [3.10807892e+00 3.43096205e+00 9.59270683e-01 7.69434496e-03
  6.30073457e-03]
 [3.80731702e-01 4.65978778e-04 9.82508797e-01 6.93375554e-01
  8.31848331e-02]]


## 1.6 np.divide() 矩阵对应位相除

In [154]:
print(np.divide(randn, randn))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 1.7 np.where() 三元表达式

In [155]:
print(np.where(randn > 0, 1, -1))

[[-1 -1  1 -1 -1]
 [-1  1 -1  1 -1]
 [-1 -1  1 -1  1]
 [-1 -1  1 -1 -1]
 [-1  1 -1  1 -1]]


# 2 统计函数

## 2.1 np.sum() 求和

In [156]:
print(np.sum(randn))

-6.637305265096461


## 2.2 np.prod() 乘积

In [157]:
print(np.prod(randn))

-1.1435125272248019e-08


## 2.3 np.min() 最小值

In [158]:
print(np.min(randn))

-1.9534057866631322


## 2.4 np.max() 最大值

In [159]:
print(np.max(randn))

1.9815278457851284


## 2.5 np.mean() 平均值

In [160]:
print(np.mean(randn))

-0.2654922106038584


## 2.6 np.std() 标准差

In [161]:
print(np.std(randn))

0.9447448598008711


## 2.7 np.var() 方差

In [162]:
print(np.var(randn))

0.8925428501201677


## 2.8 np.any() 判断是否有True的元素

In [163]:
print(np.any(randn > 0))

True


## 2.9 np.all() 判断是否所有元素都为True

In [164]:
print(np.all(randn > 0))

False


## 2.10 np.argmax() 索引最大值

In [165]:
print(np.argmax(randn))

14


## 2.11 np.argmin() 索引最小值

In [166]:
print(np.argmin(randn))

1


## 2.12 np.where() 三元表达式

In [167]:
np.where(randn > 0,1,-1)

array([[-1, -1,  1, -1, -1],
       [-1,  1, -1,  1, -1],
       [-1, -1,  1, -1,  1],
       [-1, -1,  1, -1, -1],
       [-1,  1, -1,  1, -1]])

# 3 np.unique() 函数去重

In [168]:
# 排序后降为一维数组
arr = np.array([[1,2,2],
         [2,2,3]])
unique = np.unique(arr)
print(unique)

[1 2 3]


# 4 np.sort() 排序函数

## 4.1 np.sort()会返回一个新的ndarray对象,不修改原ndarray对象

In [169]:
reshape = np.random.randint(0,25, size=(5,5))
print(np.sort(reshape))

[[ 1  7  9 16 17]
 [ 5  6  7 16 19]
 [ 2  3 12 21 22]
 [ 3  4  8 22 24]
 [ 5 10 21 22 23]]


## 4.2 ndarray.sort() 对象调用sort()会修改原ndarray对象

In [170]:
print(f'reshape 排序前:{reshape}')
reshape.sort()
print(f'reshape 排序后:{reshape}')

reshape 排序前:[[ 1  7 17  9 16]
 [ 6 19  7 16  5]
 [ 3 12  2 21 22]
 [24  4  8 22  3]
 [22 23 10 21  5]]
reshape 排序后:[[ 1  7  9 16 17]
 [ 5  6  7 16 19]
 [ 2  3 12 21 22]
 [ 3  4  8 22 24]
 [ 5 10 21 22 23]]


# 5 矩阵运算

## 5.1 numpy基础运算

In [175]:
# numpy 基本运算 
# 前提: 两个矩阵的行数和列数必须完全相同(矩阵加减)
arr1=np.array([10,20,30,40])
arr2=np.arange(4)
print(arr1)
print(arr2)
#减法运算 
print(arr1-arr2)  # 对应位置元素做减法运算(行列数相同)
#加法运算
print(arr1+arr2)  # 对应位置元素做加法运算(行列数相同)
#乘法运算
print(arr1*arr2)  # 对应位置元素做乘法运算(行列数相同)
#除法运算
print(arr1/arr2)

[10 20 30 40]
[0 1 2 3]
[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[        inf 20.         15.         13.33333333]


/var/folders/sn/slf546c97n58twkgwfy9rwth0000gn/T/ipykernel_96177/1066046467.py:14: RuntimeWarning: divide by zero encountered in divide
  print(arr1/arr2)


# 5.2 矩阵乘法

In [176]:
# 矩阵乘法  
# 定义数组
arr1=np.array([[1,2,3],
         [4,5,6]])

arr2=np.array([[1,2,3],
         [4,5,6]])

# print(f"arr1:{arr1} , {arr1.shape}")
# print(f"arr2:{arr2}, {arr1.shape}")
#矩阵乘法   行列数一致   哈达玛积
# 哈达玛积一种点对点的乘法运算 , 仅限于形状完全相同的矩阵(或者向量)
# print(arr1*arr2)
# print(np.multiply(arr1,arr2))
# 矩阵乘法  ->行列数不一致
arr3=np.array([[1,2,3],
         [4,5,6]])   # 2,3
arr4=np.array([
    [9,8],
    [6,5],
    [3,2]
    ]
)       #3,2
# print(arr3*arr4)                #报错,行列数不一致(乘法适合行列数一致场景) 
# print(np.multiply(arr3,arr4))   #报错,行列数不一致(乘法适合行列数一致场景) 
# 
#dot
# print(np.dot(arr3,arr4))   
# print(arr3.dot(arr4))       #  效果同上   
print(arr3@arr4)

#矩阵相乘 行列数不一致: A矩阵: 2行3列   B:矩阵 3行2列    A矩阵的列=B矩阵的行   结果:A行B列
# 举例子              A矩阵: 2行3列   B:矩阵 3行2列   A3列=B3行           结果:2行2列 

[[30 24]
 [84 69]]
