# 创建ndrray对象
   * 方式1 ：使用array()函数
     + 通过手动创建ndarray对象
     + 通过将python的列表、元组、其他数组等转换成ndarray对象
   * 方式2 ：使用asarray()函数
      * 通过手动创建ndarray对象
      * 通过将python的列表、元组、其他数组等转换成ndarray对象
      
# 主要区别
* array()函数和asarray()函数的区别
```javascript
numpy.asarray() 是一个用于将输入的数据转换为 NumPy 数组的方法。它的作用是将输入的数据
（比如 Python 列表、元组、其他数组等）转换为 NumPy 数组。与 numpy.array() 类似，
numpy.asarray() 会尽可能地返回一个视图（而非复制）来节省内存，只有在输入数据不可变或需要复制时才会进行复制。
```
# 总结

* numpy.array(): 适用于你需要创建一个独立副本的场景，确保输入数据不会影响原数组。

    * 总是复制数据。

    * 适用于需要生成新的数组副本的场景。

* numpy.asarray(): 适用于你希望尽量避免不必要的复制的场景，尤其是在你已经有了一个 NumPy 数组时。

    * 尽量避免复制数据，返回原数组的视图（如果数据类型一致）。

    * 如果输入不是 NumPy 数组，或者数据类型不一致，它会创建新数组。

# 何时使用 asarray() 和 array()？

> 1. 使用 asarray()：当你希望从其他数据类型（如列表、元组等）转换为 NumPy 数组时，并且希望避免额外的内存复制。如果输入已经是 NumPy 数组，它不会进行额外的复制。  



> 2. 使用 array()：当你明确需要一个新的数组副本时，确保不会影响原始数据（无论输入是否已经是 NumPy 数组）。

            

## 方式一:使用array()函数和asarray()函数常见的用法

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.asarray(a) is  a
c = np.asarray([1,2,3,4,5])
print(a)
print(b)
print(c)

[1 2 3 4 5]
True
[1 2 3 4 5]


## 方式二:使用arange()函数进行创建数组

In [ ]:
print(np.arange(1, 10, 1).reshape(3, 5))

## 方式三:使用 random()函数进行创建数组

### 1.random.rand()创建随机数组 random生成0-1的数据

In [6]:
# 不能指定范围,只生成0-1的小数
print(np.random.rand(3, 4))

[[0.91437092 0.9340763  0.83698067 0.28139318]
 [0.47815937 0.07501212 0.30567659 0.12835701]
 [0.47917417 0.14454666 0.5908587  0.00996979]]


### 2.random.randint()创建随机数组

In [7]:
# 创建一个3行4列的随机数组，数组中的元素范围是0-10的整数,不包括10,不包尾
print(np.random.randint(0, 10, size=(3, 4)))

[[9 0 2 3]
 [0 5 2 5]
 [4 7 4 0]]


### 3.uniform()创建随机数组,随机生成小数矩阵

In [10]:
# 创建一个3行4列的随机数组，数组中的元素范围是0-10的小数,不包括10,不包尾
print(np.random.uniform(0, 10, size=(3, 4)))

[[6.48376228 1.04726588 6.05419113 5.78027119]
 [3.82273129 6.0702687  5.06148875 2.04958954]
 [9.68262276 5.78696482 1.78123336 4.42636005]]


## 4.randn:标准的正态分布

In [11]:
print(np.random.randn(3, 5))

[[ 0.11266752 -0.13680456 -0.59378803 -0.58023636  1.16152578]
 [-1.40291745 -0.04481001 -0.50334097 -0.61222557  0.54894793]
 [-0.82685037 -0.52738695  0.39237545 -0.40081041 -1.19869514]]


# 数据类型的转换
* dtype 参数
* astype() 方法 将ndarray里的元素类型转换为其他类型

## 1.dtype使用实例

In [13]:
arr6 = np.arange(1, 10, 1, dtype=np.int64)
print(arr6)
print(arr6.dtype)

[1 2 3 4 5 6 7 8 9]
int64


## 2.把上述的arr6 ndarray对象的元素从int64 转换为float32

In [16]:
arr7 = arr6.astype(np.float32)
print(arr7)
print(arr7.dtype)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float32


# 创建等比和等差数列
1. np.logspace() 等比:从第二项开始与前一项的比值是一个固定的常数
2. np.linspace() 等差:从第二项开始与前一项的差值是一个固定的常数

In [18]:
# 创建等比数列
# 参数一:起始值(充当10的指数)
# 参数二:结束值(充当10的指数)
# 参数三:生成等比的个数
print(np.logspace(1, 5, 5))

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [ ]:
# 创建等差数列
# 参数一:起始值
# 参数二:结束值
# 参数三:生成等差的个数
# 参数四:是否包含结束值
# 参数五:数据类型
print(np.linspace(1, 5, 5, endpoint=True, dtype=np.int64))